# Problem 2

In [22]:
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm

In [19]:
mat_contents = sio.loadmat('07HW2_digit.mat')
train_data = np.array([mat_contents[key].astype(float) for key in mat_contents.keys() if key.startswith('train')])
test_data = np.array([mat_contents[key].astype(float) for key in mat_contents.keys() if key.startswith('test')])

In [74]:
def normalize(data):
    min_val = np.min(data)
    max_val = np.max(data)
    return (data - min_val) / (max_val - min_val)

train_data = normalize(train_data)
test_data = normalize(test_data)

In [75]:
Gammas = [2**i for i in range(-14, -5)]
Cs = [2**i for i in range(-5, 4)]

train_class = np.repeat(range(2), train_data[0].shape[0])
test_class = np.repeat(range(2), test_data[0].shape[0])
train = np.append(train_data[0, :], train_data[1, :], axis=0)
test = np.append(test_data[0, :], test_data[1, :], axis=0)

## (a)

In [76]:
acc_matrix = np.zeros((len(Gammas), len(Cs)))

for i, gamma in enumerate(Gammas):
    for j, C in enumerate(Cs):
        clf = svm.SVC(kernel='rbf', gamma=gamma, C=C)
        clf.fit(train, train_class)
        acc_matrix[i, j] = clf.score(test, test_class)

print(acc_matrix)

[[0.94  0.94  0.94  0.94  0.985 0.99  0.995 1.    1.   ]
 [0.94  0.94  0.94  0.985 0.99  0.995 1.    1.    1.   ]
 [0.94  0.94  0.985 0.99  0.995 1.    1.    1.    1.   ]
 [0.945 0.985 0.99  0.995 1.    1.    1.    1.    1.   ]
 [0.985 0.99  0.995 1.    1.    1.    1.    1.    1.   ]
 [0.99  0.995 1.    1.    1.    1.    1.    1.    1.   ]
 [0.995 1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]]


## (b)

In [77]:
acc_matrix = np.zeros((len(Gammas), len(Cs)))

for i, gamma in enumerate(Gammas):
    for j, C in enumerate(Cs):
        clf = svm.SVC(kernel='linear', gamma=gamma, C=C)
        clf.fit(train, train_class)
        acc_matrix[i, j] = clf.score(test, test_class)

print(acc_matrix)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [79]:
for d in range(1, 4):
    acc_matrix = np.zeros((len(Gammas), len(Cs)))
    for i, gamma in enumerate(Gammas):
        for j, C in enumerate(Cs):
            clf = svm.SVC(kernel='poly', gamma=gamma, C=C, degree=d)
            clf.fit(train, train_class)
            acc_matrix[i, j] = clf.score(test, test_class)

    print(f'Degeree {d}')
    print(acc_matrix)

Degeree 1
[[0.94  0.94  0.94  0.94  0.94  0.985 0.99  0.995 1.   ]
 [0.94  0.94  0.94  0.94  0.985 0.99  0.995 1.    1.   ]
 [0.94  0.94  0.94  0.985 0.99  0.995 1.    1.    1.   ]
 [0.94  0.94  0.985 0.99  0.995 1.    1.    1.    1.   ]
 [0.94  0.985 0.99  0.995 1.    1.    1.    1.    1.   ]
 [0.985 0.99  0.995 1.    1.    1.    1.    1.    1.   ]
 [0.99  0.995 1.    1.    1.    1.    1.    1.    1.   ]
 [0.995 1.    1.    1.    1.    1.    1.    1.    1.   ]
 [1.    1.    1.    1.    1.    1.    1.    1.    1.   ]]
Degeree 2
[[0.575 0.575 0.575 0.575 0.575 0.575 0.575 0.575 0.575]
 [0.575 0.575 0.575 0.575 0.575 0.575 0.575 0.575 0.575]
 [0.575 0.575 0.575 0.575 0.575 0.575 0.575 0.575 0.69 ]
 [0.575 0.575 0.575 0.575 0.575 0.575 0.69  0.84  0.92 ]
 [0.575 0.575 0.575 0.575 0.69  0.84  0.92  0.955 0.99 ]
 [0.575 0.575 0.69  0.84  0.92  0.955 0.99  0.99  0.995]
 [0.69  0.84  0.92  0.955 0.99  0.99  0.995 1.    1.   ]
 [0.92  0.955 0.99  0.99  0.995 1.    1.    1.    1.   ]
 [0.99  0.